/* SPDX-License-Identifier: BSD-3-Clause */

#ifndef _HAL_CONF_H_
#define _HAL_CONF_H_

#define SOC_RK3506
#define HAL_AP_CORE

/* TIMER5 is a free-running 24 MHz timebase used by Betaflight scheduling. */
#define SYS_TIMER TIMER5

#define HAL_DCACHE_MODULE_ENABLED
#define HAL_CRU_MODULE_ENABLED
#define HAL_CPU_TOPOLOGY_MODULE_ENABLED
#define HAL_GIC_MODULE_ENABLED
#define HAL_FLEXBUS_MODULE_ENABLED
#define HAL_FSPI_MODULE_ENABLED
#define HAL_GPIO_MODULE_ENABLED
#define HAL_I2C_MODULE_ENABLED
#define HAL_IRQ_HANDLER_MODULE_ENABLED
#define HAL_PINCTRL_MODULE_ENABLED
#define HAL_PL330_MODULE_ENABLED
#define HAL_SNOR_MODULE_ENABLED
#define HAL_SPI_MODULE_ENABLED
#define HAL_TIMER_MODULE_ENABLED
#define HAL_UART_MODULE_ENABLED

#define HAL_GIC_AMP_FEATURE_ENABLED
#define HAL_GPIO_IRQ_DISPATCH_FEATURE_ENABLED

#define HAL_DBG_ON
#define HAL_DBG_USING_HAL_PRINTF
#define HAL_DBG_INFO_ON
#define HAL_DBG_WRN_ON
#define HAL_DBG_ERR_ON

#endif
